### ISSUE TITLE
ARM: Crash during compilation due to missing evaluators

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#2133]
This is derived from https://github.com/eclipse/openj9/issues/706 .
OpenJDK/OpenJ9 for ARM sometimes crashes during JIT compilation at the following location in running SPECjvm98 _213_javac and _228_jack.  ARM JIT does not have the evaluators for acmplt nor acmpge, and that caused the TR::Registers passed generateTrg1Src2Instruction() to be NULL.

> (gdb) where
> #0 0x75bbdfac in OMR::Register::incTotalUseCount(unsigned int) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #1 0x75d9d5ac in generateTrg1Src2Instruction(TR::CodeGenerator*, TR_ARMOpCodes, TR::Node*, TR::Register*, TR::Register*, TR::Register*, TR::Instruction*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #2 0x75daf5e4 in OMR::ARM::TreeEvaluator::iandEvaluator(TR::Node*, TR::CodeGenerator*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #3 0x75bacb98 in OMR::CodeGenerator::evaluate(TR::Node*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #4 0x75db33e4 in OMR::ARM::TreeEvaluator::compareIntsForEquality(TR_ARMConditionCode, TR::Node*, TR::CodeGenerator*, TR::SymbolReference*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #5 0x75db39e0 in OMR::ARM::TreeEvaluator::ificmpeqEvaluator(TR::Node*, TR::CodeGenerator*) () from /home/pi/openj9/jdk/lib/libj9jit29.so

**Comment by knn-k** [comment]
I have implemented a fix (acmplt, acmpge, acmpgt, acmple), and it works fine.
See also https://github.com/eclipse/omr/issues/793 for other missing evaluators.
