### ISSUE TITLE
OMR build hang while using CMake on test 6: PortFileTest2

### ISSUE THREAD

**Issue by mw918** [eclipse/omr#4823]
I was trying to build OMR on the Ubuntu Linux subsystem, and on the PortFileTest2 of test 6, it stays on that indefinitely. I looked through some other people's builds on Jenkins, and it looks like it should take no longer than 12 seconds. Is there some common mistake that I'm making? I was following the instructions on the README https://github.com/eclipse/omr#how-do-i-use-it. The console output is:

**Comment by mw918** [comment]
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: gcexample

1: Test command: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/example/gcexample
1: Test timeout computed to be: 9.99988e+06
1: VM/GC INITIALIZED
1: configuration is MM_ConfigurationFlat
1: collector interface is MM_CollectorLanguageInterfaceImpl
1: garbage collector is MM_ParallelGlobalGC
1: allocation interface is MM_TLHAllocationInterface
1: thread allocated 1048392 tlh bytes, 0 non-tlh bytes, from 43683 allocations before NULL
1: ALL TESTS PASSED
 1/17 Test  #1: gcexample ........................   Passed    0.10 sec
test 2
      Start  2: algotest

2: Test command: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/algotest/omralgotest "--gtest_output=xml:/mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/algotest/omralgotest-results.xml" "-avltest:/mnt/c/Users/MICHAELWang/Desktop/OMR/omr/fvtest/algotest/avltest.lst"
2: Test timeout computed to be: 9.99988e+06
2: [==========] Running 168 tests from 5 test cases.
2: [----------] 2 tests from OmrAlgoTest
2: Testing hookable interface...
2: Finished testing hookable interface.
2: Algorithm Test Finished
2: total tests: 59
2: total passes: 59
2: total failures: 0
2: ALL TESTS PASSED.
2: [----------] 2 tests from OmrAlgoTest (0 ms total)
2:
2: [----------] 58 tests from OmrAlgoTest/AVLTest
2: [----------] 58 tests from OmrAlgoTest/AVLTest (1 ms total)
2:
2: [----------] 24 tests from OmrAlgoTest/PoolTest
2: [----------] 24 tests from OmrAlgoTest/PoolTest (12 ms total)
2:
2: [----------] 14 tests from OmrAlgoTest/HashtableTest
2: [----------] 14 tests from OmrAlgoTest/HashtableTest (4430 ms total)
2:
2: [----------] 70 tests from OmrAlgoTest/CollisionResilientHashtableTest
2: [----------] 70 tests from OmrAlgoTest/CollisionResilientHashtableTest (14900 ms total)
2:
2: [==========] 168 tests from 5 test cases ran. (19349 ms total)
2: [  PASSED  ] 168 tests.
2: [  ALL TESTS PASSED  ]
 2/17 Test  #2: algotest .........................   Passed   19.45 sec
test 3
      Start  3: TestBytes

3: Test command: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/coretest/TestBytes "--gtest_output=xml:/mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/coretest/TestBytes-results.xml"
3: Test timeout computed to be: 9.99988e+06
3: [==========] Running 16 tests from 1 test case.
3: [----------] Global test environment set-up.
3: [----------] 16 tests from TestBytes
3: [ RUN      ] TestBytes.CompareZeroToZero
3: [       OK ] TestBytes.CompareZeroToZero (0 ms)
3: [ RUN      ] TestBytes.CompareOneUnitToBytes
3: [       OK ] TestBytes.CompareOneUnitToBytes (0 ms)
3: [ RUN      ] TestBytes.CompareOneUnitToSmallerUnit
3: [       OK ] TestBytes.CompareOneUnitToSmallerUnit (0 ms)
3: [ RUN      ] TestBytes.IsPow2
3: [       OK ] TestBytes.IsPow2 (0 ms)
3: [ RUN      ] TestBytes.AlignedUnsafe
3: [       OK ] TestBytes.AlignedUnsafe (0 ms)
3: [ RUN      ] TestBytes.Aligned
3: [       OK ] TestBytes.Aligned (0 ms)
3: [ RUN      ] TestBytes.AlignToZero
3: [       OK ] TestBytes.AlignToZero (0 ms)
3: [ RUN      ] TestBytes.AlignToOne
3: [       OK ] TestBytes.AlignToOne (0 ms)
3: [ RUN      ] TestBytes.AlignToTwo
3: [       OK ] TestBytes.AlignToTwo (0 ms)
3: [ RUN      ] TestBytes.AlignToFour
3: [       OK ] TestBytes.AlignToFour (0 ms)
3: [ RUN      ] TestBytes.AlignToEight
3: [       OK ] TestBytes.AlignToEight (0 ms)
3: [ RUN      ] TestBytes.SaneAlignmentMaximums
3: [       OK ] TestBytes.SaneAlignmentMaximums (0 ms)
3: [ RUN      ] TestBytes.AlignToMaximumAlignment
3: [       OK ] TestBytes.AlignToMaximumAlignment (0 ms)
3: [ RUN      ] TestBytes.TautologicalAlign
3: [       OK ] TestBytes.TautologicalAlign (0 ms)
3: [ RUN      ] TestBytes.AlignAndOverflow
3: [       OK ] TestBytes.AlignAndOverflow (0 ms)
3: [ RUN      ] TestBytes.AlignMaximumSizeFor16byteAlignment
3: [       OK ] TestBytes.AlignMaximumSizeFor16byteAlignment (0 ms)
3: [----------] 16 tests from TestBytes (0 ms total)
3:
3: [----------] Global test environment tear-down
3: [==========] 16 tests from 1 test case ran. (0 ms total)
3: [  PASSED  ] 16 tests.
3: [  ALL TESTS PASSED  ]
 3/17 Test  #3: TestBytes ........................   Passed    0.26 sec
test 4
      Start  4: TestIntrusiveList

4: Test command: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/coretest/TestIntrusiveList "--gtest_output=xml:/mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/coretest/TestIntrusiveList-results.xml"
4: Test timeout computed to be: 9.99988e+06
4: [==========] Running 10 tests from 1 test case.
4: [----------] Global test environment set-up.
4: [----------] 10 tests from TestIntrusiveList
4: [ RUN      ] TestIntrusiveList.Empty
4: [       OK ] TestIntrusiveList.Empty (0 ms)
4: [ RUN      ] TestIntrusiveList.ConvertIterToConstIter
4: [       OK ] TestIntrusiveList.ConvertIterToConstIter (0 ms)
4: [ RUN      ] TestIntrusiveList.AddOne
4: [       OK ] TestIntrusiveList.AddOne (0 ms)
4: [ RUN      ] TestIntrusiveList.IterateOne
4: [       OK ] TestIntrusiveList.IterateOne (0 ms)
4: [ RUN      ] TestIntrusiveList.IterateTwo
4: [       OK ] TestIntrusiveList.IterateTwo (0 ms)
4: [ RUN      ] TestIntrusiveList.AddThenRemoveOne
4: [       OK ] TestIntrusiveList.AddThenRemoveOne (0 ms)
4: [ RUN      ] TestIntrusiveList.AddTwoThenRemoveFirst
4: [       OK ] TestIntrusiveList.AddTwoThenRemoveFirst (0 ms)
4: [ RUN      ] TestIntrusiveList.AddTwoThenRemoveSecond
4: [       OK ] TestIntrusiveList.AddTwoThenRemoveSecond (0 ms)
4: [ RUN      ] TestIntrusiveList.AddTwoThenRemoveBoth
4: [       OK ] TestIntrusiveList.AddTwoThenRemoveBoth (0 ms)
4: [ RUN      ] TestIntrusiveList.AddTwoThenRemoveBothInReverse
4: [       OK ] TestIntrusiveList.AddTwoThenRemoveBothInReverse (0 ms)
4: [----------] 10 tests from TestIntrusiveList (1 ms total)
4:
4: [----------] Global test environment tear-down
4: [==========] 10 tests from 1 test case ran. (1 ms total)
4: [  PASSED  ] 10 tests.
4: [  ALL TESTS PASSED  ]
 4/17 Test  #4: TestIntrusiveList ................   Passed    0.10 sec
test 5
      Start  5: TestTypeTraits

5: Test command: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/coretest/TestTypeTraits "--gtest_output=xml:/mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/coretest/TestTypeTraits-results.xml"
5: Test timeout computed to be: 9.99988e+06
5: [==========] Running 17 tests from 1 test case.
5: [----------] Global test environment set-up.
5: [----------] 17 tests from TestTypeTraits
5: [ RUN      ] TestTypeTraits.IntegralConst
5: [       OK ] TestTypeTraits.IntegralConst (0 ms)
5: [ RUN      ] TestTypeTraits.BooleanConstant
5: [       OK ] TestTypeTraits.BooleanConstant (0 ms)
5: [ RUN      ] TestTypeTraits.IsSame
5: [       OK ] TestTypeTraits.IsSame (0 ms)
5: [ RUN      ] TestTypeTraits.TypeAlias
5: [       OK ] TestTypeTraits.TypeAlias (0 ms)
5: [ RUN      ] TestTypeTraits.RemoveConst
5: [       OK ] TestTypeTraits.RemoveConst (0 ms)
5: [ RUN      ] TestTypeTraits.RemoveVolatile
5: [       OK ] TestTypeTraits.RemoveVolatile (0 ms)
5: [ RUN      ] TestTypeTraits.RemoveCv
5: [       OK ] TestTypeTraits.RemoveCv (0 ms)
5: [ RUN      ] TestTypeTraits.RemoveReference
5: [       OK ] TestTypeTraits.RemoveReference (0 ms)
5: [ RUN      ] TestTypeTraits.RemoveCvRef
5: [       OK ] TestTypeTraits.RemoveCvRef (0 ms)
5: [ RUN      ] TestTypeTraits.RemovePointer
5: [       OK ] TestTypeTraits.RemovePointer (0 ms)
5: [ RUN      ] TestTypeTraits.IsReference
5: [       OK ] TestTypeTraits.IsReference (0 ms)
5: [ RUN      ] TestTypeTraits.IsPointer
5: [       OK ] TestTypeTraits.IsPointer (0 ms)
5: [ RUN      ] TestTypeTraits.IsVoid
5: [       OK ] TestTypeTraits.IsVoid (0 ms)
5: [ RUN      ] TestTypeTraits.IsIntegral
5: [       OK ] TestTypeTraits.IsIntegral (0 ms)
5: [ RUN      ] TestTypeTraits.IsFloatingPoint
5: [       OK ] TestTypeTraits.IsFloatingPoint (0 ms)
5: [ RUN      ] TestTypeTraits.IsArithmetic
5: [       OK ] TestTypeTraits.IsArithmetic (0 ms)
5: [ RUN      ] TestTypeTraits.EnableIf
5: [       OK ] TestTypeTraits.EnableIf (0 ms)
5: [----------] 17 tests from TestTypeTraits (1 ms total)
5:
5: [----------] Global test environment tear-down
5: [==========] 17 tests from 1 test case ran. (1 ms total)
5: [  PASSED  ] 17 tests.
5: [  ALL TESTS PASSED  ]
 5/17 Test  #5: TestTypeTraits ...................   Passed    0.13 sec
test 6
      Start  6: porttest

6: Test command: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/porttest/omrporttest "--gtest_output=xml:/mnt/c/Users/MICHAELWang/Desktop/OMR/omr/build/fvtest/porttest/omrporttest-results.xml"
6: Test timeout computed to be: 9.99988e+06
6: [==========] Running 212 tests from 19 test cases.
6: [----------] 1 test from PortInitializationTest
6: [----------] 1 test from PortInitializationTest (0 ms total)
6:
6: [----------] 2 tests from PortFileTest
6: [----------] 2 tests from PortFileTest (39 ms total)
6:
6: [----------] 8 tests from PortHeapTest
6: [----------] 8 tests from PortHeapTest (1710 ms total)
6:
6: [----------] 8 tests from PortTest
6: [----------] 8 tests from PortTest (2 ms total)
6:
6: [----------] 10 tests from PortMemTest
6: [----------] 10 tests from PortMemTest (1048 ms total)
6:
6: [----------] 4 tests from PortDumpTest
6: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/fvtest/porttest/omrdumpTest.cpp line  173: omrdump_test_create_dump_with_NO_name omrdump_create returned: 1, with filename: Error opening "/proc/sys/kernel/core_pattern". Look for core file generated by child process with pid = 9646
6:              LastErrorNumber: -108
6:              LastErrorMessage: No such file or directory
6:
6: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/fvtest/porttest/testHelpers.cpp:109: Failure
6: Value of: 0 == numberFailedTestsInComponent
6:   Actual: false
6: Expected: true
6: Test failed!
6: [  FAILED  ] PortDumpTest.dump_test_create_dump_with_NO_name (18 ms)
6: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/fvtest/porttest/omrdumpTest.cpp line  220: omrdump_test_create_dump_with_name omrdump_create returned: 1, with filename: Error opening "/proc/sys/kernel/core_pattern". Look for core file generated by child process with pid = 9647
6:
6:              LastErrorNumber: -108
6:              LastErrorMessage: No such file or directory
6:
6: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/fvtest/porttest/testHelpers.cpp:109: Failure
6: Value of: 0 == numberFailedTestsInComponent
6:   Actual: false
6: Expected: true
6: Test failed!
6: [  FAILED  ] PortDumpTest.dump_test_create_dump_with_name (12 ms)
6: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/fvtest/porttest/omrdumpTest.cpp line  300: omrdump_test_create_dump_from_signal_handler omrdump_create returned: 1, with filename: Error opening "/proc/sys/kernel/core_pattern". Look for core file generated by child process with pid = 9648
6:              LastErrorNumber: -108
6:              LastErrorMessage: No such file or directory
6:
6: /mnt/c/Users/MICHAELWang/Desktop/OMR/omr/fvtest/porttest/testHelpers.cpp:109: Failure
6: Value of: 0 == numberFailedTestsInComponent
6:   Actual: false
6: Expected: true
6: Test failed!
6: [  FAILED  ] PortDumpTest.dump_test_create_dump_from_signal_handler (10 ms)
6: [----------] 4 tests from PortDumpTest (40 ms total)
6:
6: [----------] 4 tests from PortErrorTest
6: [----------] 4 tests from PortErrorTest (0 ms total)
6:
6: [----------] 41 tests from PortFileTest2

**Comment by fjeremic** [comment]
I just tested on my WSL instance and I can reproduce the same hang it seems. I hopped into gdb and produced a backtrace:

```
>>> bt
#0  0x00007fffff7a1eaa in __waitpid (pid=11140, stat_loc=0x7ffffffedb50, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000000008158e85 in j9process_waitfor(OMRPortLibrary*, OMRProcessHandleStruct*) ()
#2  0x00000000081589cc in waitForTestProcess(OMRPortLibrary*, OMRProcessHandleStruct*) ()
#3  0x00000000080fa949 in PortFileTest2_file_test20_Test::TestBody() ()
#4  0x00000000081b9a00 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#5  0x00000000081b3b75 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#6  0x0000000008197ca0 in testing::Test::Run() ()
#7  0x00000000081985ca in testing::TestInfo::Run() ()
#8  0x0000000008198c5d in testing::TestCase::Run() ()
#9  0x000000000819fbc6 in testing::internal::UnitTestImpl::RunAllTests() ()
#10 0x00000000081babc1 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#11 0x00000000081b497b in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#12 0x000000000819e78b in testing::UnitTest::Run() ()
#13 0x00000000080ed7e6 in RUN_ALL_TESTS() ()
#14 0x00000000080ed59e in omr_main_entry ()
#15 0x000000000815ff2c in main ()
```

It seems we are hung on the following line:
https://github.com/eclipse/omr/blob/b00a624c42b33c88adbecd2d33e14d36f5d8b172/fvtest/porttest/omrfileTest.cpp#L2347

Looking at the test it seems to be waiting for a child process to finish. However on WSL the child process seems to be a zombie process on my system:

```
fjeremic@FILIP-IBM:/tmp/omr/build$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
fjeremic 11061 11060  0 13:42 tty7     00:00:00 -bash
fjeremic 11134 11061  0 13:48 tty7     00:00:01 gdb --args /tmp/omr/build/fvtest/porttest/omrporttest --gtest_filter=*PortFileTest2.file_test20
fjeremic 11136 11134  0 13:48 tty7     00:00:00 /tmp/omr/build/fvtest/porttest/omrporttest --gtest_filter=*PortFileTest2.file_test20
fjeremic 11140 11136  0 13:48 tty7     00:00:00 [omrporttest] <defunct>
fjeremic 11141 11136  0 13:48 tty7     00:00:00 [omrporttest] <defunct>
fjeremic 11156  2018  0 13:57 tty6     00:00:00 ps -ef
```

I also cannot attach to the process because it is a zombie:

```
fjeremic@FILIP-IBM:/tmp/omr/build$ sudo gdb -p 11140
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 11140
warning: process 11140 is a zombie - the process has already terminated
ptrace: No such process.
```

I'm not sure if the `waitForTestProcess` function handles this properly. @rwy0717, @youngar, @dnakamura thoughts?

**Comment by dnakamura** [comment]
Short Version:
There are 2 issues here

- The test is failing is failing locking files which is a known issue with WSL microsoft/WSL#1927

- The test is written improperly, and a test failure results in a hang

**Comment by fjeremic** [comment]
Thanks Devin. I don't think we can fix the first issue since it is WSL related, but we should fix the second issue. i.e. if the test fails it should not hang. We should fail gracefully even on WSL.

**Comment by dnakamura** [comment]
agreed. Also to be clear the second issue is not limited to WSL. The test will hang on any platform where the test fails
