### ISSUE TITLE
zos builds still using git://github.com which now fails

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#6291]
Recent PR builds are failing on the zos platform because git://github.com is no longer accepted.

E.g. from https://ci.eclipse.org/omr/job/PullRequest-zos_390-64/3329/console
```
> git fetch --no-tags --force --progress -- git://github.com/eclipse/omr.git +refs/pull/6269/merge:refs/remotes/origin/pr/6269/merge # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git://github.com/eclipse/omr.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1001)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1242)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:68)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:310)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)
Caused by: hudson.plugins.git.GitException: Command "git fetch --no-tags --force --progress -- git://github.com/eclipse/omr.git +refs/pull/6269/merge:refs/remotes/origin/pr/6269/merge" returned status code 128:
stdout: 
stderr: fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

The usual fix for this sort of thing is to use https://github.com instead.

**Comment by keithc-ca** [comment]
The URL should be `git@github.com:eclipse/omr.git` instead of `git://github.com/eclipse/omr.git`.
I don't think https will work (on z/OS).

**Comment by keithc-ca** [comment]
I wasn't aware that `git:` was ever a supported URL scheme, but according to https://git-scm.com/docs/git-clone, it

> does no authentication and should be used with caution on unsecured networks
