### ISSUE TITLE
dwarfdump-classic in Xcode 13 does not work on AArch64 macOS

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#6491]
DwarfParser.cpp calls a command `dwarfdump-classic` in Xcode.
I found that the command in Xcode 13 crashes immediately on AArch64 macOS, even with the `--version` option only.
See the result below on a build server running macOS 11.4.

```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic --version
Segmentation fault: 11
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump --version
Apple LLVM version 13.0.0 (clang-1300.0.29.3)
  Optimized build.
  Default target: arm64-apple-darwin20.5.0
  Host CPU: vortex
$ xcodebuild -version
Xcode 13.1
Build version 13A1030d
$ sw_vers
ProductName:    macOS
ProductVersion: 11.4
BuildVersion:   20F71
```

**Comment by knn-k** [comment]
An example of OpenJ9 build failure from https://openj9-jenkins.osuosl.org/job/Build_JDK17_aarch64_mac_Personal/84/consoleText :
```
[2022-04-21T06:29:47.756Z] Tools summary:
[2022-04-21T06:29:47.756Z] * Boot JDK:       openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode) (at /Users/jenkins/bootjdks/jdk17)
[2022-04-21T06:29:47.756Z] * Toolchain:      clang (clang/LLVM from Xcode 13.0)
[2022-04-21T06:29:47.756Z] * C Compiler:     Version 13.0.0 (at /usr/bin/clang)
[2022-04-21T06:29:47.756Z] * C++ Compiler:   Version 13.0.0 (at /usr/bin/clang++)


[2022-04-21T06:33:16.120Z] sh: line 1: 55206 Segmentation fault: 11  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9ddr_misc29.dylib.dSYM/Contents/Resources/DWARF/libj9ddr_misc29.dylib 2>&1
[2022-04-21T06:33:16.120Z] /bin/sh: line 1: 55198 Segmentation fault: 11  /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/omr_ddrgen /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9ddr_misc29.dylib.dSYM/Contents/Resources/DWARF/libj9ddr_misc29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9gc29.dylib.dSYM/Contents/Resources/DWARF/libj9gc29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libjclse29.dylib.dSYM/Contents/Resources/DWARF/libjclse29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9jvmti29.dylib.dSYM/Contents/Resources/DWARF/libj9jvmti29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9prt29.dylib.dSYM/Contents/Resources/DWARF/libj9prt29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9trc29.dylib.dSYM/Contents/Resources/DWARF/libj9trc29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9shr29.dylib.dSYM/Contents/Resources/DWARF/libj9shr29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9thr29.dylib.dSYM/Contents/Resources/DWARF/libj9thr29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9vrb29.dylib.dSYM/Contents/Resources/DWARF/libj9vrb29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libj9vm29.dylib.dSYM/Contents/Resources/DWARF/libj9vm29.dylib /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/libomrsig.dylib.dSYM/Contents/Resources/DWARF/libomrsig.dylib --show-empty --macrolist /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/ddr_info/sets/j9ddr.macros --excludes /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/openj9/runtime/ddr/excludes --blob /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/j9ddr.dat --superset /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/superset.dat --overrides /Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/openj9/runtime/ddr/overrides
[2022-04-21T06:33:16.120Z] make[10]: *** [/Users/jenkins/workspace/Build_JDK17_aarch64_mac_Personal/build/macosx-aarch64-server-release/vm/runtime/j9ddr.dat] Error 139
```

**Comment by knn-k** [comment]
The `dwarfdump-classic` command in Xcode 12 works as expected on my machine running macOS 11.6.5.

```
% /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic --version
@(#)PROGRAM:dwarfdump-classic  PROJECT:dwarfutils-195.1
% xcodebuild -version
Xcode 12.5.1
Build version 12E507
% sw_vers
ProductName:    macOS
ProductVersion: 11.6.5
BuildVersion:   20G527
```

**Comment by knn-k** [comment]
Related PR in the past: #3708
FYI @keithc-ca

**Comment by knn-k** [comment]
[dwarfdump-output.zip](https://github.com/eclipse/omr/files/8550705/dwarfdump-output.zip)

Attached please find output from `dwarfdump-classic` (Xcode 12) and `dwarfdump` (Xcode 13) for libj9ddr_misc29.dylib.dSYM/Contents/Resources/DWARF/libj9ddr_misc29.dylib for AArch64.
I don't include the Xcode 12 `dwarfdump` output because it was exactly the same as that from Xcode 13 `dwarfdump`.

**Comment by knn-k** [comment]
I ran macOS builds with PR #5800 in https://github.com/eclipse-openj9/openj9/pull/14420, both x86-64 and aarch64, which finished successfully.

**Comment by knn-k** [comment]
I ran extended.functional on x86-64 macOS in https://github.com/eclipse-openj9/openj9/pull/14921, with and without the `dwarfdump` change PR #5800.  It shows that you can build OpenJ9 for macOS using `dwarfdump`, but the generated runtime does not work as expected.

- Without PR 5800: Successful.  https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Personal/36/
- With PR 5800: Many `MemoryFault` failures with DDR tests in https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Personal/35/ as shown below.  :

```
 [ERR] Apr 25, 2022 7:40:12 PM com.ibm.j9ddr.vm29.events.DefaultEventListener corruptData
 [ERR] SEVERE: Error initializing GCExtensions
 [ERR] com.ibm.j9ddr.corereaders.memory.MemoryFault: Memory Fault reading 0x5341524D56394A 
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.memory.AbstractMemory.getBytesAt(AbstractMemory.java:184)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.memory.AbstractMemory.getBytesAt(AbstractMemory.java:176)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.memory.AbstractMemory.getLongAt(AbstractMemory.java:241)
```

**Comment by keithc-ca** [comment]
Can you check what version of DWARF is being used? I don't think DTFJ is prepared for version 5.

**Comment by knn-k** [comment]
The `dwarfdump` output in https://github.com/eclipse/omr/issues/6491#issuecomment-1107938690 says version 4.

```
.debug_info contents:
0x00000000: Compile Unit: length = 0x000001a8, format = DWARF32, version = 0x0004, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x000001ac)
```

The binary was built in a job at https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_mac_Personal/63/ .

**Comment by keithc-ca** [comment]
With #5800 I was able to build for aarch64 macOS with DDR support.

**Comment by knn-k** [comment]
Yes, you can build.  But it does not work as expected as I wrote in https://github.com/eclipse/omr/issues/6491#issuecomment-1109763365.

**Comment by keithc-ca** [comment]
> Yes, you can build. But it does not work as expected as I wrote in [#6491 (comment)](https://github.com/eclipse/omr/issues/6491#issuecomment-1109763365).

The key file produced for DDR is `j9ddr.dat`. Other than a problem with the old version of `DwarfParser` fixed by https://github.com/eclipse/omr/pull/5800, the two versions of `j9ddr.dat` generated with or without https://github.com/eclipse/omr/pull/5800 capture the same types, the same field offsets and the same constants. So, I don't have an explanation for your observations. We'll need to have a closer look at the troublesome core files.

**Comment by knn-k** [comment]
@keithc-ca 
Sorry, I didn't notice you had updated #5800 yesterday.  I tried running DDR tests on AArch64 macOS with the latest #5800 locally, and it seems to work.
Thank you!

**Comment by pshipton** [comment]
I think this can be closed now.
