### ISSUE TITLE
Intermittent failures in omrsysinfo_get_process_start_time 

### ISSUE THREAD

**Issue by tajila** [eclipse/omr#7469]
`omrsysinfo_get_process_start_time` is used in CRIUSupport to determine the start time of the restored process. We are seeing intermittent failures as a result of using this API.

```
Stack Dump = io.openliberty.checkpoint.internal.criu.CheckpointFailedException: j9sysinfo_get_process_start_time failed with errno=-384
        at io.openliberty.checkpoint.internal.openj9.ExecuteCRIU_OpenJ9.dump(ExecuteCRIU_OpenJ9.java:63)
        at io.openliberty.checkpoint.internal.CheckpointImpl.checkpoint(CheckpointImpl.java:396)
        at io.openliberty.checkpoint.internal.CheckpointImpl.checkpointOrExitOnFailure(CheckpointImpl.java:303)
        at io.openliberty.checkpoint.internal.CheckpointImpl.check(CheckpointImpl.java:297)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at com.ibm.ws.kernel.feature.internal.FeatureManager.checkServerReady(FeatureManager.java:868)
        at com.ibm.ws.kernel.feature.internal.FeatureManager.update(FeatureManager.java:829)
        at com.ibm.ws.kernel.feature.internal.FeatureManager.processFeatureChanges(FeatureManager.java:931)
        at com.ibm.ws.kernel.feature.internal.FeatureManager$1.run(FeatureManager.java:714)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:298)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1595)
Caused by: org.eclipse.openj9.criu.SystemRestoreException: j9sysinfo_get_process_start_time failed with errno=-384
        at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:538)
        at io.openliberty.checkpoint.internal.openj9.ExecuteCRIU_OpenJ9.dump(ExecuteCRIU_OpenJ9.java:55)
        ... 12 more
Caused by: openj9.internal.criu.SystemRestoreException: j9sysinfo_get_process_start_time failed with errno=-384
        at java.base/openj9.internal.criu.InternalCRIUSupport.checkpointJVMImpl(Native Method)
        at java.base/openj9.internal.criu.InternalCRIUSupport.checkpointJVM(InternalCRIUSupport.java:997)
        at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:530)
        ... 13 more
```

**Comment by tajila** [comment]
Just confirming that the issue is seen on ub22

**Comment by ThanHenderson** [comment]
> seeing intermittent failures

How intermittent (or what is the occurrence rate)? Did we just start seeing this? And is it only happening in this benchmark?

>  likely possible that this issue can be recreated without Liberty

We can likely create a simpler test where we see the failure; I haven't seen this through my simple testing of the `checkpointJVM` APIs. It'd be nice to know the command which was run that resulted in this test failure.

> im still getting more info on the environment 

Were there any other diagnostic data collected from the runs with this failure?

**Comment by singh264** [comment]
Dear @pshipton and @tajila, I would like to inform you that this issue can be closed as the test for `omrsysinfo_get_process_start_time` was removed leaving the problem unaffected.

**Comment by ThanHenderson** [comment]
@singh264 The latter part of this comment: https://github.com/eclipse-omr/omr/issues/7469#issuecomment-2383494754 indicates there is still some work to be done to enable this for criu. The patch removes the test because it isn't supported, but doesn't fix the underlying problem.

**Comment by singh264** [comment]
Problem is not solved, @tajila, and I would like to work on it.
